// schema.js — Fonte única de verdade do formulário.
// Os `key` espelham o AnamneseData do TRINUS-APP onde há sobreposição,
// para que um lead convertido pré-preencha a anamnese completa.

export const COUNTRY_CODES = [
  { code: '+351', label: '🇵🇹 +351 Portugal' },
  { code: '+55', label: '🇧🇷 +55 Brasil' },
  { code: '+34', label: '🇪🇸 +34 Espanha' },
  { code: '+44', label: '🇬🇧 +44 Reino Unido' },
  { code: '+1', label: '🇺🇸 +1 EUA / Canadá' },
  { code: '+33', label: '🇫🇷 +33 França' },
  { code: '+49', label: '🇩🇪 +49 Alemanha' },
  { code: '+41', label: '🇨🇭 +41 Suíça' },
  { code: '+244', label: '🇦🇴 +244 Angola' },
  { code: '+258', label: '🇲🇿 +258 Moçambique' },
]

// Tipos suportados: text, email, phone, number, date, radio, chips, textarea, slider, consent
export const STEPS = [
  {
    id: 'contato',
    icon: '👋',
    title: 'Contato',
    subtitle: 'Vamos começar pelo básico. Como falamos contigo?',
    fields: [
      { key: 'nome_completo', label: 'Nome completo', type: 'text', required: true, placeholder: 'O teu nome' },
      { key: 'email', label: 'E-mail', type: 'email', required: true, placeholder: 'nome@dominio.com' },
      { key: 'whatsapp', label: 'WhatsApp', type: 'phone', required: true, placeholder: 'Número (sem o indicativo)' },
      { key: 'data_nascimento', label: 'Data de nascimento', type: 'date' },
      { key: 'sexo', label: 'Sexo', type: 'radio', required: true, options: ['Masculino', 'Feminino', 'Prefiro não informar'] },
      { key: 'cidade', label: 'Cidade onde vives', type: 'text', placeholder: 'Ex: Lisboa' },
      { key: 'profissao', label: 'Profissão e rotina de trabalho', type: 'text', placeholder: 'Ex: Designer, sentado a maior parte do dia' },
    ],
  },
  {
    id: 'objetivo',
    icon: '🎯',
    title: 'Objetivo',
    subtitle: 'O que te traz aqui? Quero perceber o teu porquê.',
    fields: [
      { key: 'objetivo', label: 'Qual o teu principal objetivo?', type: 'radio', required: true,
        options: ['Emagrecer', 'Ganhar massa muscular', 'Condicionamento', 'Saúde geral', 'Estética', 'Performance'] },
      { key: 'motivacao_principal', label: 'Por que esse objetivo agora? O que mudou?', type: 'textarea', required: true,
        placeholder: 'Ex: Quero ter mais energia e preparar-me para um evento...' },
      { key: 'prazo', label: 'Em quanto tempo gostarias de ver resultado?', type: 'radio',
        options: ['1 mês', '3 meses', '6 meses', 'Sem pressa'] },
      { key: 'tentou_antes', label: 'Já tentaste antes? O que funcionou e o que não funcionou?', type: 'textarea',
        placeholder: 'Opcional — conta-me a tua experiência' },
    ],
  },
  {
    id: 'medidas',
    icon: '📏',
    title: 'Medidas',
    subtitle: 'Um ponto de partida para acompanhar a tua evolução.',
    fields: [
      { key: 'altura_cm', label: 'Altura (cm)', type: 'number', required: true, placeholder: 'Ex: 175', min: 100, max: 250 },
      { key: 'peso_avaliacao', label: 'Peso atual (kg)', type: 'number', required: true, placeholder: 'Ex: 75.5', min: 30, max: 300, step: 0.1 },
      { key: 'percentual_gordura', label: '% de gordura (se souberes)', type: 'number', placeholder: 'Ex: 18', min: 1, max: 70, step: 0.1 },
    ],
  },
  {
    id: 'saude',
    icon: '🩺',
    title: 'Saúde',
    subtitle: 'Segurança em primeiro lugar. Marca tudo o que se aplica.',
    fields: [
      { key: 'lesoes_anteriores', label: 'Lesões (atuais ou passadas)', type: 'chips', required: true, color: 'red',
        options: ['Ombro', 'Joelho', 'Lombar', 'Cervical', 'Tornozelo', 'Punho', 'Quadril', 'Cotovelo', 'Nenhuma'] },
      { key: 'condicoes_medicas', label: 'Tens alguma condição médica?', type: 'chips', color: 'orange',
        options: ['Hipertensão', 'Diabetes', 'Cardíaca', 'Hérnia', 'Respiratória', 'Outra', 'Nenhuma'] },
      { key: 'liberacao_medica', label: 'Tens liberação médica para atividade física?', type: 'radio',
        options: ['Sim', 'Não', 'Não preciso'] },
      { key: 'dor_movimento', label: 'Sentes dor em algum movimento específico?', type: 'textarea',
        placeholder: 'Opcional — ex: dor no joelho ao agachar' },
      { key: 'gestante', label: 'Estás gestante ou em pós-parto recente?', type: 'radio',
        options: ['Sim', 'Não', 'Não se aplica'], showIf: (d) => d.sexo === 'Feminino' },
    ],
  },
  {
    id: 'treino',
    icon: '🏋️',
    title: 'Treino',
    subtitle: 'Onde, quando e como treinas — para montar algo realista.',
    fields: [
      { key: 'nivel', label: 'Como avalias o teu nível?', type: 'radio',
        options: ['Iniciante', 'Intermediário', 'Avançado'] },
      { key: 'tempo_treino', label: 'Há quanto tempo treinas?', type: 'text', placeholder: 'Ex: 6 meses, ou "a começar do zero"' },
      { key: 'local_treino', label: 'Onde vais treinar?', type: 'radio', required: true,
        options: ['Ginásio', 'Casa', 'Ar livre', 'Misto (varia)'] },
      { key: 'frequencia_semanal', label: 'Quantos dias por semana consegues treinar?', type: 'radio', required: true,
        options: ['2', '3', '4', '5', '6'] },
      { key: 'tempo_sessao', label: 'Quanto tempo por sessão?', type: 'radio',
        options: ['30 min', '45 min', '60 min', '+60 min'] },
      { key: 'horario_treino', label: 'Qual horário costumas treinar?', type: 'radio',
        options: ['Manhã', 'Tarde', 'Noite', 'Varia'] },
      { key: 'equipamentos', label: 'Que equipamentos tens disponíveis?', type: 'textarea',
        placeholder: 'Ex: halteres, elásticos, barra fixa... (ou "ginásio completo")' },
    ],
  },
  {
    id: 'compromisso',
    icon: '💪',
    title: 'Estilo de vida',
    subtitle: 'Quase lá! Isto ajuda-me a perceber o teu momento.',
    fields: [
      { key: 'qualidade_sono', label: 'Qualidade do teu sono', type: 'slider', min: 1, max: 10, default: 6, labels: ['Muito ruim', 'Excelente'] },
      { key: 'nivel_stress', label: 'Nível de stress no dia a dia', type: 'slider', min: 1, max: 10, default: 5, labels: ['Baixo', 'Alto'] },
      { key: 'alcool', label: 'Consomes álcool?', type: 'radio', options: ['Não', 'Socialmente', 'Frequentemente'] },
      { key: 'fuma', label: 'Fumas?', type: 'radio', options: ['Não', 'Às vezes', 'Sim, diariamente'] },
      { key: 'prioridade', label: 'Quanto este objetivo é prioridade hoje?', type: 'slider', required: true, min: 1, max: 10, default: 7, labels: ['Pouco', 'Muito'] },
      { key: 'acompanhamento', label: 'Preferes acompanhamento próximo ou só o plano para executar sozinho?', type: 'radio', required: true,
        options: ['Acompanhamento próximo', 'Só o plano'] },
      { key: 'observacoes', label: 'Algo mais que queiras partilhar?', type: 'textarea', placeholder: 'Opcional' },
      { key: 'consentimento', label: 'Declaro que as informações são verdadeiras e entendo que devo procurar liberação médica caso tenha qualquer condição de saúde.', type: 'consent', required: true },
    ],
  },
]
